// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-3')['BButton']
    BCard: typeof import('bootstrap-vue-3')['BCard']
    BCardBody: typeof import('bootstrap-vue-3')['BCardBody']
    BCardText: typeof import('bootstrap-vue-3')['BCardText']
    BCol: typeof import('bootstrap-vue-3')['BCol']
    BCollapse: typeof import('bootstrap-vue-3')['BCollapse']
    BContainer: typeof import('bootstrap-vue-3')['BContainer']
    BFormInput: typeof import('bootstrap-vue-3')['BFormInput']
    BFormSelect: typeof import('bootstrap-vue-3')['BFormSelect']
    BImg: typeof import('bootstrap-vue-3')['BImg']
    BImgLazy: typeof import('bootstrap-vue-3')['BImgLazy']
    BNavbar: typeof import('bootstrap-vue-3')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-3')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue-3')['BNavbarNav']
    BNavbarToggle: typeof import('bootstrap-vue-3')['BNavbarToggle']
    BNavItem: typeof import('bootstrap-vue-3')['BNavItem']
    BPagination: typeof import('bootstrap-vue-3')['BPagination']
    BRow: typeof import('bootstrap-vue-3')['BRow']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheNavbar: typeof import('./src/components/TheNavbar.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    VacancyCard: typeof import('./src/components/VacancyCard.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
